trainer: adaptok_ar_trainer

train_dataset:
  name: video_dataset
  args:
    root_path: data/metadata
    split: train
    frame_num: $frame_num$
    rand_augment: 'no'
    csv_file: $csv_file$
    cls_vid_num: '-1_-1'
    crop_size: $input_size$
    scale: 1.0
    aspect_ratio: 1.0
    rand_flip: 'yes'
    frame_rate: 'native'
    use_all_frames: false
    pre_load: false
    ar_ann_path: 'none'

  loader:
    batch_size: $batch_size$
    num_workers: $num_workers$

test_dataset:
  name: video_dataset
  args:
    root_path: data/metadata
    frame_num: $frame_num$
    cls_vid_num: '-1_-1'
    crop_size: $input_size$
    frame_rate: 'native'
    use_all_frames: false
    pre_load: false
    ar_ann_path: 'none'

  csv_paths: {k400_val: ''}
  loader:
    batch_size: $batch_size$
    num_workers: $num_workers$

model:
  name: llama-abs-XS
  args:
    mode: train_adap_ar
    num_classes: 400
    cls_token_num: 1
    token_dropout_p: 0.1
    use_fixed_pe: false
    with_block_sep: true
    tot_blocks: 4

vae:
  name: adaptok
  checkpoint: ''
  version: 'sd'
  eval_deterministic: true
  offline_mode: true

ar:
  num_samples: 32
  num_save_wandb: 8
  sample_batch_size: 32
  cfg_scale: 1.0
  cfg_interval: -1
  temperature: 1.0
  top_k: 0
  top_p: 1.0

optimizer:
  name: adamw
  args: {lr: 6.e-4, betas: [0.9, 0.95], weight_decay: 0.05}
  lr_type: cosine
  lr_step_pcts: 0.9_0.95
  warmup_epoch: 1
  min_lr_mult: 0.01

fvd_real_stats_path: ''
fid_real_stats_path: ''

max_epoch: 49
eval_epoch: 100000000
vis_epoch: 100000000
latest_interval: 2
save_epoch: 100000000
save_best: false
autostop: false
stepwise_logging: true
stepwise_logging_interval: 50
ema_decay: '_'

use_amp: true
amp_dtype: 'bfloat16'
vae_force_fp32: false
compile: false
compile_mode: 'default'
flash_attn: false

dump_ckt: 'no'
dump_pred: 'no'
dump_video: 'no'

clip_grad_max_norm: 1.0

init_checkpoint: ''
